### ISSUE TITLE
link broken: 'notes taken during outage'

### ISSUE THREAD

**Issue by gabecase** [charlax/professional-programming#21]
![broken_fix](https://user-images.githubusercontent.com/8486998/51712785-7f9db000-1ff5-11e9-9463-c8defd7e6bd3.png)

**Comment by gabecase** [comment]
link leads to a google page that just says
"Sorry, the file you have requested has been deleted.

Make sure that you have the correct URL and the owner of the file hasn't deleted it."

**Comment by charlax** [comment]
Indeed, removed. Thanks!
