### ISSUE TITLE
my first 10 minutes on a server primer for securing ubuntu is unavailable

### ISSUE THREAD

**Issue by maathor** [charlax/professional-programming#33]
I suggest you to use the gist https://gist.github.com/SimplGy/7dc513c725219b08e4632a09686f945d
It contains all command lines described in the blog, unfortunately unavailable.

**Comment by charlax** [comment]
Mmmh indeed. The gist does not provide any context though, and is very terse. Not sure it's super useful. So I'm just removing the link.

Thanks for the notice!
