### ISSUE TITLE
Broken link: A plain english introduction to CAP Theorem

### ISSUE THREAD

**Issue by rhsobr** [charlax/professional-programming#35]
In section Databases -> A plain english introduction to CAP Theorem

**Comment by timClicks** [comment]
That link works for me.. It's also available on the [Wayback Machine](https://web.archive.org/web/20200713011407/http://ksat.me/a-plain-english-introduction-to-cap-theorem)

**Comment by dmark** [comment]
I get a 404 from the link from github. The link in github has a trailing `/`. Remove the trailing `/` and the link works:

404: http://ksat.me/a-plain-english-introduction-to-cap-theorem/
Works: http://ksat.me/a-plain-english-introduction-to-cap-theorem

**Comment by timClicks** [comment]
That would make sense. Perhaps my browser is removing the trailing slash..

**Comment by rhsobr** [comment]
Sry, I haven't noticed it.

Trailing `/` also works here.

**Comment by charlax** [comment]
Indeed, thanks for the notice! This is fixed in dfd5b56.
