### ISSUE TITLE
Caching explained redirects to an online gambling site

### ISSUE THREAD

**Issue by alerycserrania** [charlax/professional-programming#62]
https://cachingexplained.com/

https://github.com/charlax/professional-programming/blob/0d3b63c77d0b4a7bebd57c5d1141c6853e683653/README.md?plain=1#L369

**Comment by iOSMaL** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
