### ISSUE TITLE
[Broken links] Signs that you're a <good|bad> programmer

### ISSUE THREAD

**Issue by rodrigoborgesdeoliveira** [charlax/professional-programming#66]
The following links are broken:
- [Signs that you're a good programmer](http://www.yacoset.com/Home/signs-that-you-re-a-good-programmer)
- [Signs that you're a bad programmer](http://www.yacoset.com/Home/signs-that-you-re-a-bad-programmer)

Any chance any of you have an alternative link/backup?

**Comment by charlax** [comment]
Yes, I found this one: https://skatgame.net/mburo//courses/350/signs-that-you-re-a-good-programmer.html

Will fix, thanks!

**Comment by Sudouble** [comment]
来件已收到，我会尽快处理！

**Comment by iOSMaL** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
