### ISSUE TITLE
[More challenging projects every programmer should try] - link is now broken

### ISSUE THREAD

**Issue by mhunter1728** [charlax/professional-programming#85]
[More challenging projects every programmer should try](https://web.eecs.utk.edu/~azh/blog/morechallengingprojects.html): ray tracer, key-value store web API, web browser, stock trading bot.

Somebody seems to have scraped it to this page: https://www.joyk.com/dig/detail/1608507940352050  but I can't find a new official home for it.

**Comment by charlax** [comment]
Thanks - ifxed.
